Repository GSG-G13/Nour-Khaled, pull requests merged in 2023-03, with the labels that each got.

#3 2 adding html css 1
  Nour-Khaled.jpg
  css/all.min.css
  css/main.css
  css/normalize.css
  index.html
  main.js
  webfonts/fa-brands-400.ttf
  webfonts/fa-brands-400.woff2
  webfonts/fa-regular-400.ttf
  webfonts/fa-regular-400.woff2
  webfonts/fa-solid-900.ttf
  webfonts/fa-solid-900.woff2
  webfonts/fa-v4compatibility.ttf
  webfonts/fa-v4compatibility.woff2
Labels: documentation

#5 adding the functionality to main.js also modifying index.html and sty…
  .vscode/settings.json
  css/main.css
  index.html
  main.js
Labels: documentation

#8 adding documentaion
  css/main.css
  index.html
  main.js
Labels: approved

#9 adding pagination function
  css/main.css
  index.html
  main.js
Labels: waiting-approve

#11 modifying
  main.js
Labels: waiting-approve

#13 fixing a bug in filter
  main.js
Labels: approved

#15 finish
  code1.jpg
  css/main.css
  css/tv.css
  index.html
  main.js
  tv.html
  tv.js
Labels: approved

#17 final update of css files
  css/main.css
  css/tv.css
Labels: waiting-approve

#19 fixing a bug with local storage
  main.js
  tv.js
Labels: waiting-approve

#21 Final
  main.js
  tv.js
Labels: waiting-approve

#25 modifying the code according to Nada's review
  main.js
  tv.js
Labels: approved
